### PR TITLE
Dev jean

### PR DESCRIPTION
**Pull request by ffoodd**

### CODE REVIEW

**Comment by ffoodd** [comment]
Wanna check my own commits @Lausselloic , please :') ?

**Comment by ffoodd** [comment]
Everything is messed up for now, website-side:

- Migrating to Boosted 5 is not over: markup has not been updated, 
- scripts and files aren't correctly ignored from Git…
- etc.

**Comment by Lausselloic** [comment]
> Wanna check my own commits @Lausselloic , please :') ?

Are you sure that global install of bower and grunt are no more needed and could be removed from readme? Otherwise just mention that the user need to have them installed without mentioning the command lines

Other commits LGTM

**Comment by ffoodd** [comment]
Bower is useless since we can use NPM; and Grunt is in devDependencies already, so `npm run grunt` works fine and removes the need to install Grunt globally :)

There're quite a few things messed up still on this branch, mostly with ignoring files: some filenames are now hashed, allowing them to not match the `.gitignore` rules anymore… Which explains this:

image

Currently trying to clean things up…

**Comment by ffoodd** [comment]
Feels more accurate :
image

Still questionning:
- banner repeated several times in dist/css files
- hashes in file names, going froma single one to 7 or 9 hashes…

Apart from that, I think this PR is cleaner. I'd need to take some time to test build and extension in both Chromium and Firefox before merging — to make sure it works as intended.

**Pull request merged**
