### PR TITLE
Bye, Grunt

### LINKED ISSUE #78: Refactor all the thing
Project architecture is kinda outdated now, using Grunt on a Yeoman boilerplate through Bower for Node10… 

We need to upgrade the project architecture to ease maintenance, contribution and evolution—but also to fix #75, #73 and #59, for example (maybe  #71 too, by the way).

However it needs a plan! Here we go.

## Requirements

- [x] Drop Bower entirely: #79 
- [x] Drop IE11 Add-on: #83
- [x] ~Drop server version~: still useful.
- [ ] Drop Grunt, switching to npm scripts: this require a deep understanding of what's actually going on with current Grunt scripts: #85 

 ## Improvements

- [x] Add `.editorconfig` at least, 
- And linters at some point → #89
- Add a zip script to package WebExtension → #90
- Allow npm publication for server version → #86
- Automate changelog (based on conventionnal-commit tooling, like on Boosted) → #91
- Update Netlify configuration and deployments → #92
- deploy docs from `/docs` folder and drop `gh-pages` branch → #92
  - needs some cleanup from `gh-pages`, which is quite messy right now…
-  use GitHub Actions at some point to run tests and/or deploy a preview on Netlify → #93
- improve documentation website (probably another topic, but hey… who knows?): use 11ty or something? → #94
- optimize images: using SVGO, but also imgmin — and use modern image format like webp? → #95
- Refactor HTML & CSS → #96
- Refactor JavaScript … #97

Anything else?

### PR DESCRIPTION
**Pull request by ffoodd**
Close #78

Translating current Grunt scripts onto meaningful language before trying to migrate them.

- List task
- Explain what they do (and how, maybe)
- Find npm script alternatives

Everything will need to be battle-tested, obviously. And as a matter of fact, tooling could / should be aligned with Boosted's repo IMO.

### `default`

Combining `build`, `buildchromeext` and `docs`.

#### `build`

- [x] `'clean:distserveur'`
  - cleans up `dist/serveur/`
  - `rm -rf dist/serveur/`
- [x] `'copy:dist'`
  - Copy assets to `dist/serveur/`
  - `cp -r {images,css,fonts,*.txt,**/*.html} dist/serveur/` **(!)**
   - why is the licence file called `COPYING.txt`?
- [x] `'useminPrepare'`
  - defines `testpage.html` ' `<!-- build:js js/toolbar-min.js -->` comment as JS stack to bundle — but does nothing on its own…
- [x] `'concat:dist'`
  - insert banner code (mainly YeoMan's config path) in lieu of `use strict`,
  - and concat each file of the stack ↑ in `dist/serveur/js/toolbar.js`
- [x] `'uglify:distserveur'`
  - minify `toolbar.js` to `toolbar-min.js`
  - probably use **terser** here (as in Boosted)
- [x] `'cssmin'`
  - minify `classic-toolbar.css` to `classic-toolbar.min.css`
  - should definitely use Sass here
  - there's an `autoprefixer` task, called nowhere…
- [x] `'filerev'`
  - ~~rename files "for browser caching purposes": mostly adding hashes to filenames for CSS, fonts and images.~~
  - ~~is this really useful? Feels like a simple version query string would do the job, isn't it?~~
  - - **Dropped**
- [x] `'usemin'`
  - ~~replaces assets inclusion with their optimized counterparts (minified and renamed dist files)~~
  - ~~wow, we need to drop this entirely.~~
  - **Dropped**
- [x] `'htmlmin'`
  - minify HTML files: drop white spaces, boolean attributes values, CDATA comments and optional tags…
  - from `dist/serveur/` to `dist/serveur` :)
- [x] `'replace:replacements'`
  - ~~replaces calls to local JS files to use absolute URLs: feels useless to me :/~~
- [x] `'replace:replacementsHelp'`
  - used to insert the `toolbar-min.js` script before closing `</body>`.
- [x] `'usebanner'`
  - Insert banner (name, version, ©, etc.) on top of some JS (`mask` and `toolbar*`) and CSS files.
  - Could be in the sources, no need for such things.

#### `buildchromeext`

- [x] `'clean:chromeext'`
  - cleans up `dist./WebExtension/` folder
  - `rm -rf dist/WebExtension/`
- [x] `'copy:chromeext`
  - Copy assets from `app/` to `dist/WebExtension`
  - `cp -r app/{WebExtension,images,css,help,language,js} !js/{start.server,UciCookie}.js dist/WebExtension/ && cp app/conf/WebExtension/ dist/WebExtension/conf/` **(!)**
- [x] `'replace:chromeext'`
  - seems to replace `start` and `Uci` JS filenames with WebExtension ones in WebExtension's help page.

#### `docs`

- [x] `'copy:docs'`→ `cp -r node_modules/boosted/dists/{css,fonts} dist/serveur/ docs/`

### `serve`

- [x] `'build'`
- [x] `'docs'`
- [x] `'connect:livereload'`
  - starts a webserver locally (port `9010`)
  - opens the local testpage
  - could use `servor` or anything…
- [x] `'watch'`
  - it includes a JSHint task, but the `.jshintrc` config file is missing…
  - watch for changes (HTML, CSS, JS and images files) in its `livereload` entry

#### To question

- [x] ~~Deliver `.woff2` files only for fonts~~ → Further enhancement, see #78
- [x] `app/` should be `src/`
- [x] `language` could be in `js/`,
- [x] ~~`help` could be at the root~~ → Would require redirections, so skipping this for now. Maybe `demo/` would be needed instead, for consistency?
- [x] why are we copying `.html` files and assets in the server version? What's really needed here? IMO the `server` version only needs minified JS, CSS, fonts and images…
- [x] what's the `data/` folder for, in `WebExtension/`? Looks like images…
- [x] ~~`docs/` contains tons of git-ignored files… There's probably a way to not output them there!~~ → **They're already deployed on docs website so safer to keep them for now…**

### CODE REVIEW

**Comment by ffoodd** [comment]
Or should I go the other way around, trying to list what's needed and start from scratch?

**Comment by Lausselloic** [comment]
COPYING.txt due to how to use GPL: https://www.gnu.org/licenses/gpl-howto.html

**Comment by ffoodd** [comment]
I suggest we start from the ground: migrate existing scripts, then improve the content itself as much as possible.

**Comment by ffoodd** [comment]
The project is currently missing a zip task for the WebExtension folder.

**Comment by ffoodd** [comment]
Notes:
- `copy:ext` could be simpler if `conf/` folders where at the same place in `app/` and `dist/`…

**Comment by ffoodd** [comment]
Still bugging with CSS files' banner: tried `postcss-banner` and `postcss-header`, `postcss-replace` and `shx sed` ithout any luck. Each of them use `$npm_package_name` as a string. Needs to understand what's happening!

**Comment by ffoodd** [comment]
@Lausselloic I'm considering splitting build scripts for serveur, extension and docs to make it clearer. Could be done later, though.

**Pull request merged**
